version: '3.9'

services:
  backend:
    image: ghcr.io/redisventures/redis-arxiv-search:latest
    env_file:
      - .env
    expose:
      - "8888"
    ports:
      - "8888:8888"
    depends_on:
      - "redis-vector-db"
  redis-vector-db:
    build:
      context: ./redis-vector-db
      dockerfile: Dockerfile
    volumes:
      - redis-vector-db:/var/lib/redis
    ports:
      - 6379:6379
      - 8001:8001


volumes:
  redis-vector-db: