version: '3.9'

services:
  backend:
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
    depends_on:
      - "redis"
  redis:
    image: redis:8.0-M03
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s
