version: '3.7'

services:
  redis-vector-db:
    build:
      context: ./redis-vector-db
      dockerfile: Dockerfile
    volumes:
      - ./redis-data:/data/
    ports:
      - 6379:6379
      - 8001:8001
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5
  backend:
    image: ghcr.io/redisventures/redis-arxiv-search:latest
    environment:
      DEPLOYMENT: "dev"
      REDIS_HOST: "redis-vector-db"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "testing123"
      REDIS_DB: 0
    expose:
      - "8888"
    ports:
      - "8888:8888"
    depends_on:
      - "redis-vector-db"

volumes:
  redis-vector-db: